name: Fetch Token Price

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch GeckoTerminal pool data
        run: node assets/fetch-price.js

      - name: Commit and push data
        run: |
          git config user.name "Tidekeeper"
          git config user.email "tidekeeper@dinero.com"
          git add data/price.json
          git commit -m "Update price data [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/solanadinero/computersite.git HEAD:main

